name: rashail_gallery_view
description: rashail_gallery_view is a flutter plugin that is used to create an image gallery for flutter application
version: 0.0.1+1
homepage: "https://github.com/Developers-Rashail-Infotech/rashail_gallery_view/"

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^0.13.5
  get: ^4.6.5
  blur: ^3.1.0
  simple_shadow: ^0.3.1
  rashail_image_zoom: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
# flutter:
#   plugin:
#     platforms:
#       android:
#         package: com.example.rashail_image_zoom
#         pluginClass: RashailGallery
#       ios:
#         pluginClass: RashailGallery
